name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3

      - name: Run tests
        run: gradle test

      - name: Archive JUnit HTML report
        uses: actions/upload-artifact@v3
        with:
          name: junit-html
          path: build/reports/tests/test

      - name: Archive JUnit XML report
        uses: actions/upload-artifact@v3
        with:
          name: junit-xml
          path: build/test-results/test/**.xml
